apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golearn
  annotations:
    networking.k8s.io/ingress.class: "nginx" # Use spec.ingressClassName instead of the deprecated annotation
spec:
  rules:
    - host: eezzy.com.ng
      http:
        paths:
          - path: /backends
            backend:
              service:
                name: golearn-service
                port:
                  number: 30000
