apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golearn
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: eezzy.com.ng
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: golearn-service
                port:
                  number: 30000
        